[Content]
RootPassword=ukirescue
Autologin=yes
Hostname=uki-rescue
Bootloader=none
Bootable=false
Timezone=UTC
Keymap=us
Locale=C.UTF-8
KernelCommandLine=quiet systemd.show_status=yes
Ssh=no
WithRecommends=no
WithDocs=no
#KernelModules=.*

#	-/drivers/ata/
#	/drivers/ata/ahci.ko.zst
#	/drivers/ata/ata_piix.ko.zst
#	/drivers/ata/libahci.ko.zst
#	/drivers/ata/libata.ko.zst
#	-/drivers/base/
