# needssslcertforbuild

[Include]
Include=mkosi-obs

[Distribution]
Distribution=opensuse
Release=tumbleweed

[Output]
OutputDirectory=mkosi.output
Format=none
ImageVersion=0.0

[Content]
Bootable=false
Packages=
        uki-rescue-image-arch-deps
        aaa_base
        bash
        bash-completion
        btrfsprogs
        busybox-adduser
        busybox-bind-utils
        ca-certificates
        ca-certificates-mozilla
        coreutils
        coreutils-systemd
        curl
        dosfstools
        e2fsprogs
        efibootmgr
	exfatprogs
        fwupd
        gdb
        glibc
        glibc-locale-base
        gnu_ddrescue
        gpg2
        gptfdisk
        iproute2
        iputils
        kernel-default
        kernel-firmware-all
        kernel-firmware-network
        kernel-firmware-usb-network
        less
        libnss_usrfiles2
        libseccomp2
        login_defs
        ltrace
        lvm2
	man-online
        mdadm
        mtools
        netcat-openbsd
        openSUSE-build-key
        openSUSE-release
        openSUSE-release-appliance-custom
        openssh
        parted
        patterns-base-hardware
        pciutils
        procps
        rdii-helper
        rdii-helper
        shim
        strace
	sysextmgr
        systemd
        systemd-boot
        systemd-networkd
        systemd-presets-branding-openSUSE
	systemd-resolved
        tar
        timezone
        traceroute
        udev
        usbutils
        vim-small
        wget
        xfsprogs
