[Config]
Dependencies=base

[Output]
Format=sysext
Overlay=yes
ImageId=uki-rescue-utilities
Output=%i-%v.%a
OutputExtension=sysext.raw
ManifestFormat=json

[Validation]
Verity=no

[Content]
CleanPackageMetadata=yes
BaseTrees=%O/base
Packages=
	lvm2
	pciutils
	usbutils
	wget

[Build]
Environment=SYSTEMD_REPART_OVERRIDE_FSTYPE_ROOT=squashfs
Environment=SYSEXT_SCOPE=system
